2. Importação de bibliotecas

In [1]:
%pip install -q -U pandas numpy matplotlib seaborn

Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.2 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
sns.set_style('whitegrid')
plt.rcParams['figure.figsize'] = (12, 6)

1. Geração de dados com Pandas e Numpy

In [3]:
print('Gerando um conjunto de dados...')

np.random.seed(42)

data = {
    'ID_Pedido': range(1001, 1101),
    'Data_Compra': pd.to_datetime(pd.date_range(start = '2026-07-01', periods = 100, freq ='D')) - pd.to_timedelta(np.random.randint(0, 30, size = 100), unit = 'd'),
    'Cliente_ID': np.random.randint(100, 150, size = 100),
    'Produto': np.random.choice(['Smartphone', 'Notebook', 'Fone de Ouvido', 'Smartwatch', 'Teclado Mecânico'], size = 100),
    'Categoria': ['Eletrônicos', 'Eletrônicos', 'Acessórios', 'Acessórios', 'Acessórios'] * 20,
    'Quantidade': np.random.randint(1, 5, size = 100),
    'Preco_Unitario': [5999.90, 8500.00, 799.50, 2100.00, 850.00] * 20,
    'Status_Entrega': np.random.choice(['Entregue', 'Pendente', 'Cancelado'], size = 100, p = [0.8, 0.15, 0.05])
}

df_vendas = pd.DataFrame(data)

print('\nIntroduzindo problemas nos dados para a limpeza...')

df_vendas.loc[5:10, 'Quantidade'] = np.nan
df_vendas.loc[20:22, 'Status_Entrega'] = np.nan
df_vendas.loc[30, 'Cliente_ID'] = np.nan

df_vendas = pd.concat([df_vendas, df_vendas.head(3)], ignore_index=True)

df_vendas['Preco_Unitario'] = df_vendas['Preco_Unitario'].astype(str)
df_vendas.loc[15, 'Preco_Unitario'] = 'valor_invalido' 
df_vendas['Cliente_ID'] = df_vendas['Cliente_ID'].astype(str)

df_vendas.loc[50, 'Quantidade'] = 50 

print('Geração de dados concluída com sucesso! ')

Gerando um conjunto de dados...

Introduzindo problemas nos dados para a limpeza...
Geração de dados concluída com sucesso!

C:\Users\gabriel.aalves\AppData\Local\Temp\ipykernel_1188\7752048.py:7: Pandas4Warning: 'd' is deprecated and will be removed in a future version. Please use 'D' instead of 'd'.
  'Data_Compra': pd.to_datetime(pd.date_range(start = '2026-07-01', periods = 100, freq ='D')) - pd.to_timedelta(np.random.randint(0, 30, size = 100), unit = 'd'),

2. Análise Exploratória dos Dados (EDA)

In [5]:
df_vendas.info()

<class 'pandas.DataFrame'>
RangeIndex: 103 entries, 0 to 102
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   ID_Pedido       103 non-null    int64
 1   Data_Compra     103 non-null    datetime64[us]
 2   Cliente_ID      102 non-null    str
 3   Produto         103 non-null    str
 4   Categoria       103 non-null    str
 5   Quantidade      97 non-null     float64
 6   Preco_Unitario  103 non-null    str
 7   Status_Entrega  100 non-null    str
dtypes: datetime64[us](1), float64(1), int64(1), str(5)
memory usage: 6.6 KB

In [6]:
# Verificando valores ausentes
print(df_vendas.isna().sum())

ID_Pedido         0
Data_Compra       0
Cliente_ID        1
Produto           0
Categoria         0
Quantidade        6
Preco_Unitario    0
Status_Entrega    3
dtype: int64

In [9]:
print(f'Número de linhas duplicadas: {df_vendas.duplicated().sum()}')

Número de linhas duplicadas: 3

In [10]:
df_vendas.describe()

         ID_Pedido                 Data_Compra  Quantidade
count   103.000000                         103   97.000000
mean   1049.087379  2026-08-02 09:33:12.233009    3.103093
min    1001.000000         2026-06-05 00:00:00    1.000000
25%    1023.500000         2026-07-07 12:00:00    2.000000
50%    1049.000000         2026-07-31 00:00:00    3.000000
75%    1074.500000         2026-08-29 12:00:00    4.000000
max    1100.000000         2026-10-07 00:00:00   50.000000
std      29.733821                         NaN    4.954973

In [8]:
df_vendas.describe(include=[object])

C:\Users\gabriel.aalves\AppData\Local\Temp\ipykernel_1188\578709507.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df_vendas.describe(include=[object])

       Cliente_ID     Produto   Categoria Preco_Unitario Status_Entrega
count         102         103         103            103            100
unique         45           5           2              6              3
top         113.0  Smartwatch  Acessórios         8500.0       Entregue
freq            5          29          61             21             83